"""F1.2 (synthetic overlay), F1.3 (fake-cash labelling) and F1.4 (mandated
body text + LATENCY_NOT_EXERCISED_IN_BAR_MODE), as pure functions over a
parsed run.json dict. No metric computation anywhere in this file.
"""
from __future__ import annotations

import html
from typing import Any

VENUE_VERIFIED = "venue_verified"

# bar-data-backtest-annex-v1 SS1's sentence, verbatim. This build's reading
# list is specs/2026-09-13-ema-crossover-btc-1h-rules-and-dashboard-v1.md
# (SS0/SS9 only), specs/2026-09-13-run-output-contract-v1.md, and
# tests/fixtures/runs/ -- it does not include the annex itself. The sentence
# below is copied verbatim from the hand-authored reference
# tests/fixtures/runs/20260913T091500Z-fixture-completed-cd34ef56/report.md,
# which quotes it with its citation, rather than re-derived from memory.
BAR_DATA_ANNEX_SENTENCE = (
    "This result was computed on bar data. No spread, depth, queue position or "
    "intrabar path was observed. Every execution cost here is a proxy over a "
    "swept coefficient, not a measurement. No fill model is validated by this "
    "run, and this result carries no information about tradeable size."
)
BAR_DATA_ANNEX_CITATION = "bar-data-backtest-annex-v1 §1"

# cost-and-fill-model-v1 SS13.2's sentence is NOT in this build's reading
# list, so its verbatim text is not available here -- the same gap the
# reference report.md fixture flagged rather than paraphrase from memory.
# The work order itself (20260913-0911-cto-to-frontend-developer) glosses it
# in F1.4 as "only real fills validate a fill model"; that gloss, attributed
# as the CTO's own paraphrase and not claimed as the spec's exact wording, is
# what renders below. Flagged back to the CTO in the return report.
COST_MODEL_SENTENCE_GLOSS = (
    "Only real fills validate a fill model. No simulated fill on this page, "
    "however carefully modelled, is evidence that the model matches what a "
    "live order would actually receive."
)
COST_MODEL_SENTENCE_CITATION = "cost-and-fill-model-v1 §13.2 (CTO paraphrase; exact spec text not in this build's reading list)"

LATENCY_NOTE = (
    "LATENCY_NOT_EXERCISED_IN_BAR_MODE — latency parameters have no effect "
    "on the modelled fill price in bar mode. A populated latency field must "
    "never be read as an applied one."
)


def _data_source(run: dict[str, Any]) -> dict[str, Any] | None:
    ds = run.get("data_source")
    return ds if isinstance(ds, dict) else None


def synthetic_notice(run: dict[str, Any]) -> tuple[str, str, str] | None:
    """Default-deny notice as UNESCAPED plain text: (headline, body,
    source_string), or None when data_source.class is exactly
    "venue_verified". `source_string` is "" when there is none to show.
    Shared by the HTML overlay and the report.md renderer so the two cannot
    disagree about whether, or how, a result is flagged as not-market-data."""
    ds = _data_source(run)

    if ds is not None and ds.get("class") == VENUE_VERIFIED:
        return None

    if ds is None:
        return (
            "PROVENANCE MISSING",
            "This run carries no data_source field at all. Per the "
            "default-deny rule, absence is treated as unverified: this "
            "result's data origin is unknown and must not be read as "
            "market data of any kind.",
            "",
        )

    cls = str(ds.get("class", "unknown"))
    source = ds.get("source")
    source_text = str(source) if source else ""
    if cls == "synthetic_fixture":
        return (
            "SYNTHETIC DATA — NOT MARKET DATA",
            "Every value on this chart is generated by an arithmetic "
            "fixture. This result says nothing about BTC or any other "
            "market.",
            source_text,
        )
    return (
        "UNVERIFIED DATA SOURCE",
        f"data_source.class is '{cls}', not 'venue_verified'. This "
        "chart's data provenance has not been verified and must not "
        "be read as validated market data.",
        source_text,
    )


def synthetic_overlay_html(run: dict[str, Any]) -> str:
    """Default-deny: render the overlay unless data_source.class is exactly
    "venue_verified". Covers three cases the work order names explicitly:
    a synthetic fixture, a third-party/unverified source, and a run whose
    data_source field is missing outright. There is no close/dismiss control
    anywhere in this markup -- not hidden by CSS, absent from the DOM.
    """
    notice = synthetic_notice(run)
    if notice is None:
        return ""
    headline, body, source = notice
    esc = lambda s: html.escape(s, quote=False)  # noqa: E731
    source_line = (
        f'<p class="overlay-source-string">source: <code>{esc(source)}</code></p>' if source else ""
    )
    return (
        '<div class="synthetic-overlay" data-nondismissible="true" '
        'role="alert" aria-live="assertive">'
        f"<p class=\"overlay-headline\">{esc(headline)}</p>"
        f"<p class=\"overlay-body\">{esc(body)}</p>"
        f"{source_line}"
        "</div>"
    )


def fake_cash_axis_label_html(axis_name: str = "Equity") -> str:
    """F1.3: an equity/currency axis label carries FAKE or SIMULATED
    adjacent to it. No currency symbol appears anywhere in this package
    without this qualifier beside it."""
    safe_name = html.escape(axis_name)
    return (
        f'<p class="fake-cash-axis-label">{safe_name} axis — '
        '<strong>FAKE / SIMULATED units</strong>, not real currency</p>'
    )


def fake_cash_figure_html(formatted_value: str) -> str:
    """Wrap an already-formatted (never computed here) currency figure with
    its mandatory FAKE/SIMULATED qualifier. `formatted_value` must already be
    unit-formatted by the caller from a run.json currency-unit metric string
    -- this function does no arithmetic and accepts any string verbatim."""
    safe_value = html.escape(formatted_value)
    return f'<span class="fake-cash-figure">{safe_value} <strong>(SIMULATED)</strong></span>'


def mandated_disclaimers_html() -> str:
    """F1.4: the two mandated sentences as visible body text, plus the
    LATENCY_NOT_EXERCISED_IN_BAR_MODE note. Rendered unconditionally on
    every view this package produces -- not a tooltip, not a collapsed
    panel, not a modal."""
    return (
        '<section class="mandated-disclaimers" aria-label="Required disclaimers">'
        f'<p class="disclaimer bar-data-annex">{html.escape(BAR_DATA_ANNEX_SENTENCE)} '
        f'<cite>&mdash; {html.escape(BAR_DATA_ANNEX_CITATION)}</cite></p>'
        f'<p class="disclaimer cost-model">{html.escape(COST_MODEL_SENTENCE_GLOSS)} '
        f'<cite>&mdash; {html.escape(COST_MODEL_SENTENCE_CITATION)}</cite></p>'
        f'<p class="disclaimer latency-not-exercised">{html.escape(LATENCY_NOTE)}</p>'
        "</section>"
    )
